TrackmaniaIndia/TMIndiaBot

cogs/trackmania.py, util/trackmania/tm2020/totd.py
=> fix totd breaking if not uploaded to tmx, fix #56

bot/cogs/birthdays/set_birthday.py, bot/constants.py, bot/resources/json/birthdays.json
=> SetBirthday command sends a message to the `#mod-log` channel

bot/utils/birthdays.py, bot/utils/tasks.py
=> Add support for Multiple birthdays on one day

README.md, UPDATES.md
Radically change the README and create `UPDATES.md`
=> README Overhaul

pre-run/linux.sh, pre-run/windows.bat
Make `windows.bat` and automatically clone TrackmaniaLeaderboard and TMIndiaBotApi
=> Pre-Run Updates

bot/cogs/birthdays/remove_username.py, bot/utils/birthdays.py
=> Remove Birthday Command

bot/cogs/birthdays/add_birthday.py, bot/cogs/birthdays/remove_username.py, bot/cogs/birthdays/set_birthday.py, bot/utils/birthdays.py
=> More checks for birthdays

bot/cogs/backend/error_handler.py
=> error handler message in channel

bot/utils/cotd_util.py, bot/utils/tasks.py
=> fix totd task saving correct totd with wrong date

bot/utils/trackmania.py
=> fix broken emojis in player details

bot/resources/json/ids.json, bot/utils/trackmania.py
=> Fix COTD Details function for people who did not play a single cotd

bot/cogs/trackmania/cotd_details.py, bot/cogs/trackmania/player_details.py
Update to py-tmio v0.4.0 and update commands to use the new inbuilt functions.
Add average stats to cotddetails.
=> Update to py-tmio v0.4.0

bot/cogs/quoting/save_quote.py
=> Prevent quoting messages sent by the bot or empty strings, Fix #193

bot/cogs/trackmania/date_totd.py
Gets a TOTD of a date given by the player.
=> Get TOTD of a specific date.

bot/cogs/trackmania/search_player.py, requirements.txt
Search for a player with a given username.
=> Player Search command with a username

bot/cogs/quoting/get_quote.py, bot/cogs/quoting/last_quote.py, bot/cogs/quoting/rand_quote.py, bot/cogs/quoting/show_quote.py, bot/resources/guild_data/940194031370129478/quotes.json, bot/utils/quote.py
Created a `get_quote` command to get a quote with the specific quote-number.
=> `show-quote` command.

bot/cogs/backend/error_handler.py, bot/cogs/trackmania/player_details.py
=> Put flag in PlayerDetails paginator's embed's titles.

bot/cogs/backend/on_ready.py, bot/resources/json/statuses.json
Added server count, member count and bot version
Close #237
=> Dynamically generated statuses

bot/cogs/backend/logging.py, bot/cogs/backend/on_ready.py, bot/cogs/birthdays/add_birthday.py, bot/cogs/birthdays/remove_birthday.py, bot/cogs/trackmania/player_details.py, bot/cogs/trophies/add_player_tracking.py, bot/utils/moderation.py
=> Error fallbacks while sending messages to specific channels (hopefully)

bot/cogs/birthdays/remove_birthday.py, bot/utils/birthdays.py
=> `/remove-birthday` command and Fix `/remove-user-birthday` commands

bot/cogs/trophies/add_player_tracking.py
=> Ephemeral final message for /add-player-tracking

bot/cogs/generic/support_server.py
=> Support Server command

bot/cogs/trackmania/player_details.py, bot/cogs/trophies/remove_player_tracking.py
Fixes the descriptions of `/player-details` and `/remove-player-tracking`
Fix #314 
Fix #312
=> Fix descriptions of a few commands.

bot/cogs/trackmania/player_details.py
=> fix some display issues with `/player-details`

bot/cogs/trophies/add_player_tracking.py
=> Handle multiple player search results in `/add-player-tracking`
